export const products = [
    {
      id: 1,
      title: "Mustard OIl",
      description: "Fortune Kachi Ghani Mustard Oil Plastic Bottle  (500 ml)",
      price: "100",
      img: "https://rukminim1.flixcart.com/image/832/832/k7usyvk0/edible-oil/v/b/5/1-kachi-ghani-plastic-bottle-mustard-oil-fortune-original-imafpzwhedywqkyh.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 2,
      title: "RICE",
      description: "PUMPUM Rice Cracker Jeera Masala Papad 50 g",
      price: "300",
      img: "https://rukminim1.flixcart.com/image/832/832/kuof5ow0/fryum-papad/j/c/h/50-rice-cracker-jeera-1-masala-papad-pumpum-original-imag7qr9cxzqmzmg.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 3,
      title: "GEL",
      description: "Flipkart Supermart Home Essentials Dish Cleaning Gel  (Lemon, 0.3 L) in color",
      price: "3500",
      img: "https://rukminim1.flixcart.com/image/832/832/kqse07k0/dish-cleaning-gel/z/u/6/lemon-na-bottle-flipkart-supermart-home-essentials-original-imag4pukggjk5azg.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 4,
      title: "Besan Laddu 12",
      description: "Best Daadi's Besan Laddoo Pure Ghee Box  (120 g) ever",
      price: "90500",
      img: "https://rukminim1.flixcart.com/image/832/832/ku2zjww0/sweet-mithai/g/e/0/besan-laddoo-pure-ghee-laddu-daadi-s-original-imag7a3ynj6rbnjm.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 5,
      title: "Samsung Lemaon Dish Wash",
      description: "Home essential lemon dish wash",
      price: "25",
      img: "https://rukminim1.flixcart.com/image/832/832/khcb7gw0/dish-washing-bar/m/x/y/lemon-3-600-flipkart-supermart-home-essentials-original-imafxd9sdjhvhaav.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 6,
      title: "Seviyan",
      description: "This is best Seviyan",
      price: "35",
      img: "https://rukminim1.flixcart.com/image/832/832/ksru0sw0/vermicelli/k/t/t/vermicelli-semolina-plain-mtr-original-imag69pyfzw4fz2x.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 7,
      title: "Pasta",
      description: "This Whaet Pasta is available",
      price: "250",
      img: "https://rukminim1.flixcart.com/image/832/832/ktizdzk0/pasta/5/d/x/durum-wheat-semolina-regular-flipkart-supermart-original-imag6utbgager6pq.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 8,
      title: "Maggi",
      description: "Best Maggi Ever",
      price: "90",
      img: "https://rukminim1.flixcart.com/image/832/832/ksru0sw0/vermicelli/k/t/t/vermicelli-semolina-plain-mtr-original-imag69pyfzw4fz2x.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
    {
      id: 9,
      title: "Sweets",
      description: "Best Sweets ever",
      price: "250",
      img: "https://rukminim1.flixcart.com/image/832/832/ku2zjww0/sweet-mithai/g/e/0/besan-laddoo-pure-ghee-laddu-daadi-s-original-imag7a3ynj6rbnjm.jpeg?q=70",
      quantity: 1,
      isSoldout:false,
    },
  ];
  